name: build and publish binaries
on: [push]
jobs:
  build-binary-ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Runs cmake fetch and install
        run: ./.github/workflows/01-linux.sh '/home/runner/work/bls-signatures-cli-tool/bls-signatures-cli-tool/'
  
      - name: Create Ubuntu Jammy Jellyfish x86-64 binary
        uses: actions/upload-artifact@v2
        with: 
          name: ubuntu-jammy-jellyfish-x86-64
          path: ./build/src/runtest
  build-binary-ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Runs cmake fetch and install
        run: ./.github/workflows/01-linux.sh '/home/runner/work/bls-signatures-cli-tool/bls-signatures-cli-tool/'
  
      - name: Create Ubuntu Focal x86-64 binary
        uses: actions/upload-artifact@v2
        with: 
          name: ubuntu-focal-x86-64
          path: ./build/src/runtest
  build-binary-macos-12:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Runs cmake fetch and install
        run: ./.github/workflows/01-apple.sh '/Users/runner/work/bls-signatures-cli-tool/bls-signatures-cli-tool'
  
      - name: Create macos-12 binary
        uses: actions/upload-artifact@v2
        with: 
          name: macos-12
          path: ./build/src/runtest
  build-binary-macos-11:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Runs cmake fetch and install
        run: ./.github/workflows/01-apple.sh '/Users/runner/work/bls-signatures-cli-tool/bls-signatures-cli-tool'
  
      - name: Create macos-11 binary
        uses: actions/upload-artifact@v2
        with: 
          name: macos-11
          path: ./build/src/runtest
