name: build and publish binaries
on: [push]
jobs:
  build-binary-ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Runs cmake fetch and install
        run: ./.github/workflows/01-linux.sh '/home/runner/work/bls/bls/' ubuntu-jammy-jellyfish-x86-64.tar.gz ${{ github.ref_name }}
  
      - name: Create Ubuntu Jammy Jellyfish x86-64 binary
        uses: actions/upload-artifact@v2
        with: 
          name: ubuntu-jammy-jellyfish-x86-64
          path: ./build/ubuntu-jammy-jellyfish-x86-64.tar.gz
  build-binary-ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Runs cmake fetch and install
        run: ./.github/workflows/01-linux.sh '/home/runner/work/bls/bls/' ubuntu-focal-x86-64.tar.gz ${{ github.ref_name }}
  
      - name: Create Ubuntu Focal x86-64 binary
        uses: actions/upload-artifact@v2
        with: 
          name: ubuntu-focal-x86-64
          path: ./build/ubuntu-focal-x86-64.tar.gz
  build-binary-macos-11:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Runs cmake fetch and install
        run: ./.github/workflows/01-apple.sh '/Users/runner/work/bls/bls' macos11.tar.gz ${{ github.ref_name }}
  
      - name: Create macos-11 binary
        uses: actions/upload-artifact@v2
        with: 
          name: macos-11
          path: ./build/macos11.tar.gz
