name: build and publish binaries
on: 
  push:
    tags:
      - v*

jobs:
  create_release:
    runs-on: ubuntu-22.04
    outputs:
      outputreleaseid: ${{ steps.create_release.outputs.release_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release
        id: create_release
        run: ./.github/workflows/release.sh ${{ github.ref_name }} ${{ secrets.PERSONAL_ACCESS_TOKEN }} ${{ github.repository }}
  build-binary-ubuntu-22-04:
    needs: create_release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Runs cmake fetch and install
        run: ./.github/workflows/01-linux.sh '/home/runner/work/bls/bls/' bls-XVERSION-x86_64-ubuntu-22.04-gnu.tar.gz ${{ github.ref_name }}
  
      - name: Publish asset to release
        run: ./.github/workflows/publish-asset.sh '/home/runner/work/bls/bls/' bls-XVERSION-x86_64-ubuntu-22.04-gnu.tar.gz ${{ github.repository }} ${{ needs.create_release.outputs.outputreleaseid }} ${{ github.ref_name }} ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  build-binary-ubuntu-20-04:
    needs: create_release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Runs cmake fetch and install
        run: ./.github/workflows/01-linux.sh '/home/runner/work/bls/bls/' bls-XVERSION-x86_64-ubuntu-20.04-gnu.tar.gz ${{ github.ref_name }}
  
      - name: Publish asset to release
        run: ./.github/workflows/publish-asset.sh '/home/runner/work/bls/bls/' bls-XVERSION-x86_64-ubuntu-20.04-gnu.tar.gz ${{ github.repository }} ${{ needs.create_release.outputs.outputreleaseid }} ${{ github.ref_name }} ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  build-binary-macos-11:
    needs: create_release
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Runs cmake fetch and install
        run: ./.github/workflows/01-apple.sh '/Users/runner/work/bls/bls' bls-XVERSION-x86_64-macos-11-clang.tar.gz ${{ github.ref_name }}

      - name: Publish asset to release
        run: ./.github/workflows/publish-asset.sh '/Users/runner/work/bls/bls' bls-XVERSION-x86_64-macos-11-clang.tar.gz ${{ github.repository }} ${{ needs.create_release.outputs.outputreleaseid }} ${{ github.ref_name }} ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  publish-arm64:
    needs: [create_release,build-binary-macos-11, build-binary-ubuntu-20-04, build-binary-ubuntu-22-04]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: compress static assets
        run: |
          mkdir -p /home/runner/work/bls/bls/build 2>&1 > /dev/null
          cd ./bin/
          cp bls-arm64 bls
          tar cvzf /home/runner/work/bls/bls/build/bls-XVERSION-aarch64-gnu.tar.gz bls
      - name: Publish asset to release
        run: ./.github/workflows/publish-asset.sh '/home/runner/work/bls/bls/' bls-XVERSION-aarch64-gnu.tar.gz ${{ github.repository }} ${{ needs.create_release.outputs.outputreleaseid }} ${{ github.ref_name }} ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: compress windows exe 
        run: |
          cp ./bin/bls.exe bls.exe
          tar cvzf /home/runner/work/bls/bls/build/bls-XVERSION-x86_64-windows-msvc.tar.gz bls.exe
      - name: Publish asset to release
        run: ./.github/workflows/publish-asset.sh '/home/runner/work/bls/bls/' bls-XVERSION-x86_64-windows-msvc.tar.gz ${{ github.repository }} ${{ needs.create_release.outputs.outputreleaseid }} ${{ github.ref_name }} ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: compress windows exe for zip
        run: |
          cp ./bin/bls.exe bls.exe
          zip /home/runner/work/bls/bls/build/bls-XVERSION-x86_64-windows-msvc.zip bls.exe
      - name: Publish asset to release
        run: ./.github/workflows/publish-asset.sh '/home/runner/work/bls/bls/' bls-XVERSION-x86_64-windows-msvc.zip ${{ github.repository }} ${{ needs.create_release.outputs.outputreleaseid }} ${{ github.ref_name }} ${{ secrets.PERSONAL_ACCESS_TOKEN }}
