name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Runs cmake fetch and install
        run: ./.github/workflows/01-get-cmake.sh

      - name: package and upload binary
        run: ./.github/workflows/02-publish.sh '${{ secrets.GITHUB_TOKEN }}'

